//
// Created by hungr on 2022/05/18.
//

#ifndef HYPERWORLD_MARKUP_LANGUAGE_ENGINE_CASCADINGSTYLESHEETSOBJECTMODEL_H
#define HYPERWORLD_MARKUP_LANGUAGE_ENGINE_CASCADINGSTYLESHEETSOBJECTMODEL_H

namespace hwml_engine::dom::hwml {
    class CascadingStyleSheetsObjectModel {

    };
}

#endif //HYPERWORLD_MARKUP_LANGUAGE_ENGINE_CASCADINGSTYLESHEETSOBJECTMODEL_H
